require 'bundler'
Bundler.require

require_relative '../lib/tic_tac_toe.rb'
require_relative '../lib/concerns/checkable.rb'
require_relative '../lib/concerns/formattable.rb'
require_relative '../lib/concerns/getable.rb'
require_relative '../lib/concerns/printable.rb'
require_relative '../lib/concerns/validateable.rb'
require_relative '../lib/concerns/messageable.rb'
require_relative '../lib/concerns/setupable.rb'
require_relative '../lib/concerns/selectable.rb'
require_relative '../lib/board.rb'
require_relative '../lib/player.rb'
require_relative '../lib/computer_player.rb'
require_relative '../lib/human_player.rb'
require_relative '../lib/game.rb'
